[DO NOT MERGE] backfilling remaining data and test suite
rpt09-scully/paths-service pull request #2
Opened 2018-11-28 04:21 UTC by cjm771

[ ]  serve remaining routes
   - POST {trailId}/paths 
[ ] do sorting for paths/
  - GET {trailId}/paths?sortBy=date,{asc|desc}
[ ] fill 21 + 100 with backfill data since these entries dont exist
[ ] for paths that we dont have on S3, backfill this data from a set of data that we do have
[ ] supply sufficient coverage for unit tests
[ ] supply sufficient coverage for integretion tests

2018-12-03 21:54 UTC, MengRS commented
Beginning review now.

2018-12-04 00:23 UTC, MengRS commented on services/validator.js
> +      name: 'ranking',
@cjm771, curious why this is ranking and not rating for consistency sake?

2018-12-04 00:44 UTC, MengRS requested changes
@cjm771, completed review - see notes below... please review the unchecked boxes.  BTW - great job on error handling all around - way more than I did.

# General Notes on API:

- [ ] Seems like certain .gpx links do not work - I'm assuming that this is expected behavior as you need to be logged in / authenticated to see those files?
![2018-12-03_14-38-55](https://user-images.githubusercontent.com/7980628/49406193-b2b87700-f709-11e8-9b83-0c5ff8ba0589.gif)

> - Chris: yes this is the case for any entries that say `have_gpx: false`. These get backfilled on their respective `api_path_url` endpoint with a random seeded gpx file that we do have. (See: https://github.com/rpt09-scully/paths-service/tree/01_backfill_data_and_test_suite#153-backfilling-entries-via-a-seededrandom) I suppose i can also supply the backfilled_url for the fake gpx path, but likely i will not need this and its not public facing! But good catch. 

- [ ] May want to consider updating and putting the data shape of each particular path in your example-data.json (including the POST api endpoint - expected body parameters)


> - Chris : GOod thought Ill do this.


# API Testing
- [x] /paths 
`Comments:` Works great

- [ ] /:trailId/paths?sortBy={id|rating|date},{asc|desc}* 
`Comments`: Not sure if the `sort` works - can you double check to see if I entered the url correct? 
![image](https://user-images.githubusercontent.com/7980628/49405686-06c25c00-f708-11e8-9998-cabf13397462.png)

- [ ] /:trailId/recordings?sortBy={id|rating|date},{asc|desc}*
`Comments:` Same note on above on date sorting...

> - Chris: interesting, ill look into this, it seemed to be passing the tests.

- [ ] (POST) /:trailId/recordings
`Comments:` Can't get this working in postman - tried `form-data`, `x-www-form-urlencoded` and `raw`.  What am I doing wrong?
![2018-12-03_16-17-11](https://user-images.githubusercontent.com/7980628/49409809-12694f00-f717-11e8-8762-fefe4211102e.gif)

 > - Chris:  the server is expecting json and also the `xml` property is looking for an actual xml syntax string, not a url. The intention would be once, xml is validated it would be uploaded to S3. See last test in `test/integration/endpoints.test.js` for valid xml

- [x] /:trailId/heroPath
`Comments:` Works great

- [x] /paths/:pathId
`Comments:` Works great

- [x] /:trailId/trailHead
`Comments:` Works great

- [x] 100+ entries in database

2018-12-04 01:07 UTC, cjm771 commented on services/validator.js
> +      name: 'ranking',
should be rating ill revise

2018-12-04 01:18 UTC, cjm771 commented
Wow @MengRS thanks for the in depth review gifs and all! I edited your review with my comments and will revise, Not sure what's going on with sorting but ill investigate. 

Also did you manage to run and pass all the jest tests? Thanks

2018-12-04 02:14 UTC, MengRS commented
@cjm771 - thank you for the comments / clarification above!  I tested your post api endpoint now (thanks for the tip!) I must be doing something wrong, can you see why [this](https://imgur.com/a/uhX7f53) does not post into the database?

And yes, all your jest tests passed on my machine. 💃

2018-12-04 02:55 UTC, cjm771 commented
@MengRS looks like its accepting the post (i.e. no errors), i havent implemented the actual saving of the content to db as of yet. see TODO here:  https://github.com/rpt09-scully/paths-service/tree/01_backfill_data_and_test_suite#12-to-do

 See revisions i just made, realized that for dates i needed to do some preformatting before sorting so added extra tests and stuff.

2018-12-04 03:26 UTC, MengRS commented
@cjm771, ah! thanks for the note on the post! I need to learn how to read better.  

tested your date sort - works perfectly.

2018-12-04 03:26 UTC, merged

2018-12-04 03:45 UTC, cjm771 commented
Thanks ! Yeah no it was hidden in there, props to you for being so thorough✌🏽

Kind Regards,
Chris Malcolm

> On Dec 3, 2018, at 7:26 PM, MengRS <notifications@github.com> wrote:
> 
> Merged #2 into master.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.